### ISSUE TITLE
[feature request] spaces without quotes

### ISSUE THREAD

**Issue by 1vanK** [hjson/hjson-cpp#50] opened 2024-08-21 18:39 UTC
yaml-cpp allows this:

```
attributes: {Is Movable: true, Resize Border: 6 6 6 6}
```

https://github.com/dviglo2d/format_benchmarks/blob/main/result/data/yml-cpp_medium_flow.yml

It would be nice to have something like this in the library.

**Comment by trobro** [comment] 2024-08-31 10:39
Duplicate of hjson/hjson#114 and hjson/hjson#126, won't fix because of the complexities that would entail.

**Closed by trobro** 2024-08-31 10:39 UTC
